version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: Salcedo
      POSTGRES_PASSWORD: 1234
    networks:
      - mynetwork  

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork  
    environment:
      DATABASE_URL: "postgresql://Salcedo:1234@db/dbname"

networks:
  mynetwork:
    driver: bridge
